"""Pydantic AI structured output models for BusinessIntelligenceAgent phases."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


# ── Phase 1 output ───────────────────────────────────────────────────────────


class SchemaInterpretation(BaseModel):
    """Agent's understanding of the schema -- produced in Phase 1, stored for observability."""

    table_roles: dict[str, str]   # table_name -> "fact_table"|"dimension"|"lookup"|"unknown"
    column_roles: dict[str, str]  # "table.column" -> semantic role (e.g. "transaction_time")
    key_observations: list[str]   # notable structural facts the agent found


# ── Phase 2 output ───────────────────────────────────────────────────────────


class GeneratedQueryPlan(BaseModel):
    """SQL generated by the agent for each KPI and performer dimension.

    performer_queries stores BOTH rank and drill queries per entity:
        {"product": {"rank_query": "SELECT ...", "drill_query": "SELECT ..."}}
    Phase 3's drill_down tool reads drill_query from this dict.
    """

    kpi_queries: dict[str, str]                    # {kpi_name: sql_string}
    performer_queries: dict[str, dict[str, str]]   # {entity: {rank_query, drill_query}}
    skipped: list[dict[str, str]]                  # [{name, reason}]


# ── Phase 3 output ───────────────────────────────────────────────────────────


class LLMKPIResult(BaseModel):
    name: str
    label: str
    value: float
    unit: str
    vs_benchmark: str | None = None
    trend_direction: Literal["up", "down", "stable"]


class LLMPerformerInsight(BaseModel):
    entity_type: str
    entity_name: str
    metric: str
    value: float
    unit: str
    vs_average: float
    drill_down_explanation: str


class LLMTrendInsight(BaseModel):
    metric: str
    direction: Literal["up", "down", "stable"]
    magnitude: float
    timeframe: str
    explanation: str


class LLMBusinessReport(BaseModel):
    """Structured output from the BusinessIntelligenceAgent Phase 3."""

    business_health_score: int  # 0-100
    executive_summary: str  # 3-5 sentences, plain English
    kpis: list[LLMKPIResult] = []
    top_performers: list[LLMPerformerInsight] = []
    bottom_performers: list[LLMPerformerInsight] = []
    trends: list[LLMTrendInsight] = []
    opportunities: list[str] = []
    risks: list[str] = []
    skipped_kpis: list[dict[str, str]] = []   # [{name, reason}] -- surfaced to user
