name: Publish All Packages to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-dir:
          - datametronome/pulse/core
          - datametronome/pulse/postgres
          - datametronome/pulse/postgres-psycopg3
          - datametronome/pulse/postgres-sqlalchemy
          - datametronome/pulse/sqlite
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build and publish ${{ matrix.package-dir }}
      working-directory: ${{ matrix.package-dir }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        # Only publish if setup.py exists and package is ready
        if [ -f setup.py ]; then
          echo "Building and publishing ${{ matrix.package-dir }}"
          python -m build
          twine upload dist/*
        else
          echo "No setup.py found in ${{ matrix.package-dir }}, skipping"
        fi
